/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vistas;

import Clases.DAO;
import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author forlif3
 */
public class frmModalRegistrado extends javax.swing.JDialog {

    /**
     * Creates new form frmModalRegistrado
     */
    public frmModalRegistrado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();

        setSize(487, 550);
        setResizable(false);
        setLocationRelativeTo(null);
        botonInicioColor();

    }

    public void setEquipoInfo(long idEquipo, String rutUsuario) {

        DAO dao = new DAO();
        dao.obtenerDatosUsuario(rutUsuario);
     

        String[] datosUsuario = dao.obtenerDatosUsuario(rutUsuario);

// Verifica si se obtuvieron datos
        if (datosUsuario[0] != null) {
            // Muestra los datos obtenidos
             lblNombreEstudiante.setText(datosUsuario[0]);
   
           
        } else {
            System.out.println("No se encontraron datos para el RUT proporcionado.");
        }
        lblNumEquipo.setText(String.valueOf(idEquipo));
        lblRutEstudiante.setText(rutUsuario);

    }

    public void botonInicioColor() {
        btnCerrar.setBackground(new Color(0, 55, 48));

        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNumEquipo = new javax.swing.JLabel();
        lblTutulo = new javax.swing.JLabel();
        lblNombreEstudiante = new javax.swing.JLabel();
        lblRutEstudiante = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        iconUserEstudiante = new javax.swing.JLabel();
        lblEstudiante = new javax.swing.JLabel();
        sptScan = new javax.swing.JSeparator();
        lblRUT = new javax.swing.JLabel();
        iconRUT = new javax.swing.JLabel();
        sptRUT = new javax.swing.JSeparator();
        btnCerrar = new javax.swing.JButton();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumEquipo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblNumEquipo.setText("Número de equipo");
        jPanel1.add(lblNumEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        lblTutulo.setFont(new java.awt.Font("Roboto", 1, 52)); // NOI18N
        lblTutulo.setForeground(new java.awt.Color(102, 102, 102));
        lblTutulo.setText("Equipo");
        jPanel1.add(lblTutulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lblNombreEstudiante.setForeground(new java.awt.Color(102, 102, 102));
        lblNombreEstudiante.setText("Nombre Estudiante");
        jPanel1.add(lblNombreEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 216, 340, 30));

        lblRutEstudiante.setForeground(new java.awt.Color(102, 102, 102));
        lblRutEstudiante.setText("Rut estudiante");
        jPanel1.add(lblRutEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 316, 340, 30));

        lblTitulo2.setFont(new java.awt.Font("Roboto", 1, 52)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(102, 102, 102));
        lblTitulo2.setText("registrado");
        jPanel1.add(lblTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        iconUserEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/IconUserEstudiante.png"))); // NOI18N
        jPanel1.add(iconUserEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        lblEstudiante.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblEstudiante.setForeground(new java.awt.Color(102, 102, 102));
        lblEstudiante.setText("Estudiante");
        jPanel1.add(lblEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));
        jPanel1.add(sptScan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 340, 20));

        lblRUT.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblRUT.setForeground(new java.awt.Color(102, 102, 102));
        lblRUT.setText("R.U.T.");
        jPanel1.add(lblRUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        iconRUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconRUT.png"))); // NOI18N
        jPanel1.add(iconRUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, 30));
        jPanel1.add(sptRUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 340, 20));

        btnCerrar.setBackground(new java.awt.Color(0, 55, 48));
        btnCerrar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar");
        btnCerrar.setToolTipText("");
        btnCerrar.setBorderPainted(false);
        btnCerrar.setFocusPainted(false);
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCerrarMouseReleased(evt);
            }
        });
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 190, 50));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/panel_modal.png"))); // NOI18N
        jPanel1.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        btnCerrar.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseEntered
        btnCerrar.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnCerrarMouseEntered

    private void btnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseExited
        btnCerrar.setBackground(new Color(0, 55, 48));
    }//GEN-LAST:event_btnCerrarMouseExited

    private void btnCerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMousePressed
        btnCerrar.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnCerrarMousePressed

    private void btnCerrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseReleased
        btnCerrar.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnCerrarMouseReleased

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        btnCerrar.setBackground(new Color(0, 119, 103));
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmModalRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmModalRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmModalRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmModalRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmModalRegistrado dialog = new frmModalRegistrado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel iconRUT;
    private javax.swing.JLabel iconUserEstudiante;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEstudiante;
    private javax.swing.JLabel lblNombreEstudiante;
    private javax.swing.JLabel lblNumEquipo;
    private javax.swing.JLabel lblRUT;
    private javax.swing.JLabel lblRutEstudiante;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTutulo;
    private javax.swing.JSeparator sptRUT;
    private javax.swing.JSeparator sptScan;
    // End of variables declaration//GEN-END:variables
}
