
package Vistas;

import Clases.DAO;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;


public class frmModalEquipo extends javax.swing.JDialog {

    /**
     * Creates new form frmModalEquipo
     */
    public frmModalEquipo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
       try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();

        setSize(487, 510);
        setResizable(false);
        setLocationRelativeTo(null);
        botonInicioColor();
    }

    
    public void botonInicioColor() {
        btnAceptar.setBackground(new Color(0, 55, 48));
        btnCerrar.setBackground(new Color(0, 55, 48));

        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        bntMantecion = new javax.swing.JRadioButton();
        rdoBueno = new javax.swing.JRadioButton();
        iconStetting = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        iconID = new javax.swing.JLabel();
        sptUsuario = new javax.swing.JSeparator();
        txtID = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(bntMantecion);
        bntMantecion.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        bntMantecion.setForeground(new java.awt.Color(102, 102, 102));
        bntMantecion.setText("Mantención");
        jPanel1.add(bntMantecion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        buttonGroup1.add(rdoBueno);
        rdoBueno.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        rdoBueno.setForeground(new java.awt.Color(102, 102, 102));
        rdoBueno.setText("Bueno");
        jPanel1.add(rdoBueno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        iconStetting.setFont(new java.awt.Font("Roboto", 1, 52)); // NOI18N
        iconStetting.setForeground(new java.awt.Color(102, 102, 102));
        iconStetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/setting.png"))); // NOI18N
        jPanel1.add(iconStetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        lblID.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblID.setForeground(new java.awt.Color(102, 102, 102));
        lblID.setText("ID");
        jPanel1.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        iconID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/id.png"))); // NOI18N
        jPanel1.add(iconID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));
        jPanel1.add(sptUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 340, 20));

        txtID.setBackground(new java.awt.Color(234, 234, 234));
        txtID.setForeground(new java.awt.Color(102, 102, 102));
        txtID.setBorder(null);
        txtID.setCaretColor(new java.awt.Color(102, 102, 102));
        txtID.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtID.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIDFocusLost(evt);
            }
        });
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 340, 50));

        lblEstado.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(102, 102, 102));
        lblEstado.setText("Estado");
        jPanel1.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        btnCerrar.setBackground(new java.awt.Color(0, 55, 48));
        btnCerrar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar");
        btnCerrar.setToolTipText("");
        btnCerrar.setBorderPainted(false);
        btnCerrar.setFocusPainted(false);
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCerrarMouseReleased(evt);
            }
        });
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 190, 50));

        btnAceptar.setBackground(new java.awt.Color(0, 55, 48));
        btnAceptar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.setToolTipText("");
        btnAceptar.setBorderPainted(false);
        btnAceptar.setFocusPainted(false);
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAceptarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAceptarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAceptarMouseReleased(evt);
            }
        });
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 190, 50));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/panel_modal.png"))); // NOI18N
        jPanel1.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDFocusGained

    }//GEN-LAST:event_txtIDFocusGained

    private void txtIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDFocusLost

    }//GEN-LAST:event_txtIDFocusLost

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        btnCerrar.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseEntered
        btnCerrar.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnCerrarMouseEntered

    private void btnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseExited
        btnCerrar.setBackground(new Color(0, 55, 48));
    }//GEN-LAST:event_btnCerrarMouseExited

    private void btnCerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMousePressed
        btnCerrar.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnCerrarMousePressed

    private void btnCerrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseReleased
        btnCerrar.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnCerrarMouseReleased

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        btnCerrar.setBackground(new Color(0, 119, 103));
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        btnAceptar.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnAceptarMouseClicked

    private void btnAceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseEntered
        btnAceptar.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnAceptarMouseEntered

    private void btnAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseExited
        btnAceptar.setBackground(new Color(0, 55, 48));
    }//GEN-LAST:event_btnAceptarMouseExited

    private void btnAceptarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMousePressed
        btnAceptar.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnAceptarMousePressed

    private void btnAceptarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseReleased
        btnAceptar.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnAceptarMouseReleased

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        btnAceptar.setBackground(new Color(0, 119, 103));
        // Verificar si el campo txtID está vacío antes de convertirlo en un entero
        if (txtID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes ingresar el ID del equipo (Escanea el código de barras o ingrésalo manualmente)", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        long id;
        try {
            id = Long.parseLong(txtID.getText());  // Intentar convertir el ID
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

// Verificar si el equipo ya existe
        DAO dao = new DAO();
        if (dao.existeEquipo(id)) {
            JOptionPane.showMessageDialog(this, "El equipo con este ID ya está registrado.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String estado = "Disponible";
        String condicion = "";

// Verificar qué RadioButton está seleccionado
        if (rdoBueno.isSelected()) {
            condicion = rdoBueno.getText();
        } else if (bntMantecion.isSelected()) {
            condicion = bntMantecion.getText();
        } else {
            JOptionPane.showMessageDialog(this, "Debes seleccionar la condición del equipo", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

// Insertar en la base de datos
        if (dao.insertarEquipo(id, estado, condicion)) {
            JOptionPane.showMessageDialog(this, "Equipo insertado correctamente.");

            DefaultTableModel modelo = dao.mostrarEquipos();
            frmEquipos.getInstancia().mostrarEquipos();
            this.dispose();
            
        } else {
            JOptionPane.showMessageDialog(this, "Error al insertar el equipo.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmModalEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmModalEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmModalEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmModalEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmModalEquipo dialog = new frmModalEquipo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JRadioButton bntMantecion;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel iconID;
    private javax.swing.JLabel iconStetting;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblID;
    private javax.swing.JRadioButton rdoBueno;
    private javax.swing.JSeparator sptUsuario;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
