/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Clases.DAO;
import Clases.Exportar;
import java.awt.Color;

import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author forlif3
 */
public class frmPrestamos extends javax.swing.JFrame {

    /**
     * Creates new form frmPrestamos
     */
    public frmPrestamos() {
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();

        setSize(1280, 800);
        setResizable(false);
        setLocationRelativeTo(null);
        botonInicioColor();
        mostrarRegistroPrestamos();

    }

    // Método para mostrar todos los registros
    public void mostrarRegistroPrestamos() {
        DAO prestamos = new DAO();
        DefaultTableModel modelo = prestamos.mostrarRegistroPrestamos();
        tblPrestamos.setModel(modelo);
    }

// Método para inicializar los filtros de RUT y equipo
    public void inicializarFiltros() {
        btnFiltrar.addActionListener(e -> {
            String rut = txtRUT.getText().trim();
            String codigo = txtCodigo.getText().trim();

            if (!rut.isEmpty()) {
                filtrarPorRut(rut);
            } else if (!codigo.isEmpty()) {
                filtrarPorEquipo(codigo);
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese un RUT o código de equipo para filtrar.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        });
    }

// filtrar por RUT
    private void filtrarPorRut(String rut) {
        DAO dao = new DAO();
        DefaultTableModel modelo = dao.filtrarPorRut(rut);
        tblPrestamos.setModel(modelo);
    }

// filtrar por equipo
    private void filtrarPorEquipo(String codigoEquipo) {
        try {
            Long id = Long.parseLong(codigoEquipo);
            DAO dao = new DAO();
            DefaultTableModel modelo = dao.filtrarPorEquipo(id);
            tblPrestamos.setModel(modelo);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El código de equipo debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

// exportar los datos de la tabla
    private void exportarDatos() {
        Exportar exportar = new Exportar();
        try {
            exportar.exportarExcel(tblPrestamos);
            JOptionPane.showMessageDialog(this, "Datos exportados exitosamente.");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al exportar los datos: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void botonInicioColor() {
        btnExportar.setBackground(new Color(0, 55, 48));
        btnFiltrar.setBackground(new Color(0, 55, 48));
        btnExportar.setBackground(new Color(0, 55, 48));

        btnVolver.setBackground(new Color(0, 55, 48));

        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSubTitulo1 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnFiltrar = new javax.swing.JButton();
        lblSubTitulo2 = new javax.swing.JLabel();
        iconAlumnos = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        sptScan = new javax.swing.JSeparator();
        lblRUT = new javax.swing.JLabel();
        txtRUT = new javax.swing.JTextField();
        sptRUT = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrestamos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Roboto", 1, 52)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(102, 102, 102));
        lblTitulo.setText("Prestamos");
        jPanel4.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 270, 70));

        lblSubTitulo1.setFont(new java.awt.Font("Roboto", 1, 17)); // NOI18N
        lblSubTitulo1.setForeground(new java.awt.Color(102, 102, 102));
        lblSubTitulo1.setText("Sistema de gestión de equipos");
        jPanel4.add(lblSubTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(0, 55, 48));
        btnLimpiar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setToolTipText("");
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.setFocusPainted(false);
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLimpiarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseReleased(evt);
            }
        });
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        btnLimpiar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnLimpiarKeyReleased(evt);
            }
        });
        jPanel4.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 190, 50));

        btnExportar.setBackground(new java.awt.Color(0, 55, 48));
        btnExportar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnExportar.setForeground(new java.awt.Color(255, 255, 255));
        btnExportar.setText("Exportar");
        btnExportar.setToolTipText("");
        btnExportar.setBorderPainted(false);
        btnExportar.setFocusPainted(false);
        btnExportar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExportarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExportarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExportarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExportarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnExportarMouseReleased(evt);
            }
        });
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });
        jPanel4.add(btnExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 190, 50));

        btnVolver.setBackground(new java.awt.Color(0, 55, 48));
        btnVolver.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setToolTipText("");
        btnVolver.setBorderPainted(false);
        btnVolver.setFocusPainted(false);
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVolverMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnVolverMouseReleased(evt);
            }
        });
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel4.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 190, 50));

        btnFiltrar.setBackground(new java.awt.Color(0, 55, 48));
        btnFiltrar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnFiltrar.setForeground(new java.awt.Color(255, 255, 255));
        btnFiltrar.setText("Filtrar");
        btnFiltrar.setToolTipText("");
        btnFiltrar.setBorderPainted(false);
        btnFiltrar.setFocusPainted(false);
        btnFiltrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFiltrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFiltrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFiltrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFiltrarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnFiltrarMouseReleased(evt);
            }
        });
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        jPanel4.add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 190, 50));

        lblSubTitulo2.setFont(new java.awt.Font("Roboto", 1, 17)); // NOI18N
        lblSubTitulo2.setForeground(new java.awt.Color(102, 102, 102));
        lblSubTitulo2.setText("odontológicos");
        jPanel4.add(lblSubTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        iconAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/setting.png"))); // NOI18N
        jPanel4.add(iconAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 80, -1));

        lblCodigo.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(102, 102, 102));
        lblCodigo.setText("Código de equipo");
        jPanel4.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        txtCodigo.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigo.setForeground(new java.awt.Color(102, 102, 102));
        txtCodigo.setBorder(null);
        txtCodigo.setCaretColor(new java.awt.Color(102, 102, 102));
        txtCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCodigo.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        jPanel4.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 340, 50));
        jPanel4.add(sptScan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 340, 20));

        lblRUT.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblRUT.setForeground(new java.awt.Color(102, 102, 102));
        lblRUT.setText("RUT");
        jPanel4.add(lblRUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        txtRUT.setBackground(new java.awt.Color(255, 255, 255));
        txtRUT.setForeground(new java.awt.Color(102, 102, 102));
        txtRUT.setToolTipText("");
        txtRUT.setBorder(null);
        txtRUT.setCaretColor(new java.awt.Color(102, 102, 102));
        txtRUT.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtRUT.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtRUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRUTActionPerformed(evt);
            }
        });
        jPanel4.add(txtRUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 340, 50));
        jPanel4.add(sptRUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 340, 20));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 800));

        tblPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPrestamos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 780, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportarMouseClicked
        btnExportar.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnExportarMouseClicked

    private void btnExportarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportarMouseEntered
        btnExportar.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnExportarMouseEntered

    private void btnExportarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportarMouseExited
        btnExportar.setBackground(new Color(0, 55, 48));
    }//GEN-LAST:event_btnExportarMouseExited

    private void btnExportarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportarMousePressed
        btnExportar.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnExportarMousePressed

    private void btnExportarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportarMouseReleased
        btnExportar.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnExportarMouseReleased

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        btnExportar.setBackground(new Color(0, 119, 103));
        btnExportar.setBackground(new Color(0, 119, 103));
        Exportar objeto;

        try {
            objeto = new Exportar();
            objeto.exportarExcel(tblPrestamos);

        } catch (IOException ex) {
            System.out.println("Error: " + ex);
        }


    }//GEN-LAST:event_btnExportarActionPerformed

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        btnVolver.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        btnVolver.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        btnVolver.setBackground(new Color(0, 55, 48));
    }//GEN-LAST:event_btnVolverMouseExited

    private void btnVolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMousePressed
        btnVolver.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnVolverMousePressed

    private void btnVolverMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseReleased
        btnVolver.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnVolverMouseReleased

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        btnVolver.setBackground(new Color(0, 119, 103));
        frmPanelAdm obAdm = new frmPanelAdm();
        obAdm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnFiltrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiltrarMouseClicked
        btnFiltrar.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnFiltrarMouseClicked

    private void btnFiltrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiltrarMouseEntered
        btnFiltrar.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnFiltrarMouseEntered

    private void btnFiltrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiltrarMouseExited
        btnFiltrar.setBackground(new Color(0, 55, 48));
    }//GEN-LAST:event_btnFiltrarMouseExited

    private void btnFiltrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiltrarMousePressed
        btnFiltrar.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnFiltrarMousePressed

    private void btnFiltrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiltrarMouseReleased
        btnFiltrar.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnFiltrarMouseReleased

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        btnFiltrar.setBackground(new Color(0, 119, 103));

        if (txtRUT == null || txtCodigo == null || tblPrestamos == null) {
            JOptionPane.showMessageDialog(this, "Error: Un componente necesario no está inicializado.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        btnFiltrar.setBackground(new Color(0, 119, 103)); // Cambiar el color del botón

        String rut = txtRUT.getText().trim();
        String codigo = txtCodigo.getText().trim();

        if (!rut.isEmpty() && codigo.isEmpty()) {
            try {
                filtrarPorRut(rut); // Llama al método para filtrar por RUT
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al filtrar por RUT: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        } else if (!codigo.isEmpty() && rut.isEmpty()) {
            try {
                filtrarPorEquipo(codigo); // Llama al método para filtrar por Código de Equipo
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al filtrar por Código de Equipo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        } else if (!rut.isEmpty() && !codigo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese solo uno de los campos para filtrar (RUT o Código de Equipo).", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar al menos un campo para filtrar.", "Error", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtRUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRUTActionPerformed

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void btnLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarMouseEntered

    private void btnLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarMouseExited

    private void btnLimpiarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarMousePressed

    private void btnLimpiarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarMouseReleased

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

        txtRUT.setText("");
        txtCodigo.setText("");
        mostrarRegistroPrestamos();

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnLimpiarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLimpiarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel iconAlumnos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblRUT;
    private javax.swing.JLabel lblSubTitulo1;
    private javax.swing.JLabel lblSubTitulo2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JSeparator sptRUT;
    private javax.swing.JSeparator sptScan;
    private javax.swing.JTable tblPrestamos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtRUT;
    // End of variables declaration//GEN-END:variables
}
