
package Vistas;

import Clases.Importar;
import java.awt.Color;
import javax.swing.UIManager;


public class frmPanelAdm extends javax.swing.JFrame {

   
    public frmPanelAdm() {
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();

        setSize(1280, 800);
        setResizable(false);
        setLocationRelativeTo(null);
        botonInicioColor();
    }
    
    public void botonInicioColor() {
       btnAdministradores.setBackground(new Color(0, 55, 48));
        btnEquipos.setBackground(new Color(0, 55, 48));
        btnPrestamos.setBackground(new Color(0, 55, 48));
        btnPlantilla.setBackground(new Color(0, 55, 48));
        btnVolver.setBackground(new Color(0, 55, 48));
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iconSetting = new javax.swing.JLabel();
        btnAlumnos1 = new javax.swing.JButton();
        btnPrestamos = new javax.swing.JButton();
        btnPlantilla = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnEquipos = new javax.swing.JButton();
        btnAdministradores = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSubTitulo1 = new javax.swing.JLabel();
        lblSubTitulo2 = new javax.swing.JLabel();
        iconUsuarios = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/setting.png"))); // NOI18N
        jPanel1.add(iconSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 180, -1, -1));

        btnAlumnos1.setBackground(new java.awt.Color(0, 55, 48));
        btnAlumnos1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnAlumnos1.setForeground(new java.awt.Color(255, 255, 255));
        btnAlumnos1.setText("Alumnos");
        btnAlumnos1.setToolTipText("");
        btnAlumnos1.setBorderPainted(false);
        btnAlumnos1.setFocusPainted(false);
        btnAlumnos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlumnos1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlumnos1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlumnos1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAlumnos1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAlumnos1MouseReleased(evt);
            }
        });
        btnAlumnos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnos1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlumnos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 280, 270, 50));

        btnPrestamos.setBackground(new java.awt.Color(0, 55, 48));
        btnPrestamos.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnPrestamos.setForeground(new java.awt.Color(255, 255, 255));
        btnPrestamos.setText("Prestamos");
        btnPrestamos.setToolTipText("");
        btnPrestamos.setBorderPainted(false);
        btnPrestamos.setFocusPainted(false);
        btnPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrestamosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrestamosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrestamosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPrestamosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPrestamosMouseReleased(evt);
            }
        });
        btnPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamosActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 460, 270, 50));

        btnPlantilla.setBackground(new java.awt.Color(0, 55, 48));
        btnPlantilla.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnPlantilla.setForeground(new java.awt.Color(255, 255, 255));
        btnPlantilla.setText("Descargar Plantilla");
        btnPlantilla.setToolTipText("");
        btnPlantilla.setBorderPainted(false);
        btnPlantilla.setFocusPainted(false);
        btnPlantilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlantillaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPlantillaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPlantillaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPlantillaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPlantillaMouseReleased(evt);
            }
        });
        btnPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlantillaActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlantilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 520, 270, 50));

        btnVolver.setBackground(new java.awt.Color(0, 55, 48));
        btnVolver.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setToolTipText("");
        btnVolver.setBorderPainted(false);
        btnVolver.setFocusPainted(false);
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVolverMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnVolverMouseReleased(evt);
            }
        });
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 660, 190, 50));

        btnEquipos.setBackground(new java.awt.Color(0, 55, 48));
        btnEquipos.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnEquipos.setForeground(new java.awt.Color(255, 255, 255));
        btnEquipos.setText("Equipos");
        btnEquipos.setToolTipText("");
        btnEquipos.setBorderPainted(false);
        btnEquipos.setFocusPainted(false);
        btnEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEquiposMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEquiposMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEquiposMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEquiposMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEquiposMouseReleased(evt);
            }
        });
        btnEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquiposActionPerformed(evt);
            }
        });
        jPanel1.add(btnEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, 270, 50));

        btnAdministradores.setBackground(new java.awt.Color(0, 55, 48));
        btnAdministradores.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnAdministradores.setForeground(new java.awt.Color(255, 255, 255));
        btnAdministradores.setText("Administradores");
        btnAdministradores.setToolTipText("");
        btnAdministradores.setBorderPainted(false);
        btnAdministradores.setFocusPainted(false);
        btnAdministradores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdministradoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdministradoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdministradoresMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAdministradoresMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAdministradoresMouseReleased(evt);
            }
        });
        btnAdministradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministradoresActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdministradores, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 340, 270, 50));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Roboto", 1, 52)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(102, 102, 102));
        lblTitulo.setText("Panel ADM");
        jPanel4.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 300, 270, 70));

        lblSubTitulo1.setFont(new java.awt.Font("Roboto", 1, 17)); // NOI18N
        lblSubTitulo1.setForeground(new java.awt.Color(102, 102, 102));
        lblSubTitulo1.setText("Sistema de gestión de equipos");
        jPanel4.add(lblSubTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        lblSubTitulo2.setFont(new java.awt.Font("Roboto", 1, 17)); // NOI18N
        lblSubTitulo2.setForeground(new java.awt.Color(102, 102, 102));
        lblSubTitulo2.setText("odontológicos");
        jPanel4.add(lblSubTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        iconUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/IconUsuarios.png"))); // NOI18N
        jPanel4.add(iconUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 80, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 800));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/panel.png"))); // NOI18N
        BG.setText("jLabel1");
        jPanel1.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministradoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdministradoresMouseClicked
        btnAdministradores.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnAdministradoresMouseClicked

    private void btnAdministradoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdministradoresMouseEntered
        btnAdministradores.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnAdministradoresMouseEntered

    private void btnAdministradoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdministradoresMouseExited
        btnAdministradores.setBackground(new Color(0, 55, 48));
    }//GEN-LAST:event_btnAdministradoresMouseExited

    private void btnAdministradoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdministradoresMousePressed
        btnAdministradores.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnAdministradoresMousePressed

    private void btnAdministradoresMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdministradoresMouseReleased
        btnAdministradores.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnAdministradoresMouseReleased

    private void btnAdministradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministradoresActionPerformed
        btnAdministradores.setBackground(new Color(0, 119, 103));
        frmAdministradores obAdministradores = new frmAdministradores();
        obAdministradores.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdministradoresActionPerformed

    private void btnPrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamosMouseClicked
        btnPrestamos.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnPrestamosMouseClicked

    private void btnPrestamosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamosMouseEntered
       btnPrestamos.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnPrestamosMouseEntered

    private void btnPrestamosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamosMouseExited
        btnPrestamos.setBackground(new Color(0, 55, 48));
    }//GEN-LAST:event_btnPrestamosMouseExited

    private void btnPrestamosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamosMousePressed
       btnPrestamos.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnPrestamosMousePressed

    private void btnPrestamosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamosMouseReleased
        btnPrestamos.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnPrestamosMouseReleased

    private void btnPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamosActionPerformed
        btnPrestamos.setBackground(new Color(0, 119, 103));
        frmPrestamos obPrestamos = new frmPrestamos();
        obPrestamos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPrestamosActionPerformed

    private void btnPlantillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlantillaMouseClicked
        btnPlantilla.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnPlantillaMouseClicked

    private void btnPlantillaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlantillaMouseEntered
        btnPlantilla.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnPlantillaMouseEntered

    private void btnPlantillaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlantillaMouseExited
          btnPlantilla.setBackground(new Color(0, 55, 48));
    }//GEN-LAST:event_btnPlantillaMouseExited

    private void btnPlantillaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlantillaMousePressed
        btnPlantilla.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnPlantillaMousePressed

    private void btnPlantillaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlantillaMouseReleased
         btnPlantilla.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnPlantillaMouseReleased

    private void btnPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlantillaActionPerformed
        btnPlantilla.setBackground(new Color(0, 119, 103));
                Importar importar = new Importar();

        try {
            importar.descargarPlantilla();// Llama al método que muestra el JFileChooser y realiza la importación

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPlantillaActionPerformed

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        btnVolver.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        btnVolver.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
         btnVolver.setBackground(new Color(0, 55, 48));
    }//GEN-LAST:event_btnVolverMouseExited

    private void btnVolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMousePressed
       btnVolver.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnVolverMousePressed

    private void btnVolverMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseReleased
        btnVolver.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnVolverMouseReleased

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        btnVolver.setBackground(new Color(0, 119, 103));
        frmInicio panelInicio= new frmInicio();
        panelInicio.setVisible(true);
  
        this.dispose();
        
        
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEquiposMouseClicked
        btnEquipos.setBackground(new Color(0, 119, 103));
        
    }//GEN-LAST:event_btnEquiposMouseClicked

    private void btnEquiposMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEquiposMouseEntered
        btnEquipos.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnEquiposMouseEntered

    private void btnEquiposMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEquiposMouseExited
         btnEquipos.setBackground(new Color(0, 55, 48));
    }//GEN-LAST:event_btnEquiposMouseExited

    private void btnEquiposMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEquiposMousePressed
        btnEquipos.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnEquiposMousePressed

    private void btnEquiposMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEquiposMouseReleased
       btnEquipos.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnEquiposMouseReleased

    private void btnEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquiposActionPerformed
        btnEquipos.setBackground(new Color(0, 119, 103));
        frmEquipos obEquipos = new frmEquipos();
        obEquipos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEquiposActionPerformed

    private void btnAlumnos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlumnos1MouseClicked
        // TODO add your handling code here:
         btnAlumnos1.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnAlumnos1MouseClicked

    private void btnAlumnos1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlumnos1MouseEntered
        // TODO add your handling code here:
        btnAlumnos1.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnAlumnos1MouseEntered

    private void btnAlumnos1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlumnos1MouseExited
        // TODO add your handling code here:
         btnAlumnos1.setBackground(new Color(0, 55, 48));
    }//GEN-LAST:event_btnAlumnos1MouseExited

    private void btnAlumnos1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlumnos1MousePressed
        // TODO add your handling code here:
        btnAlumnos1.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnAlumnos1MousePressed

    private void btnAlumnos1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlumnos1MouseReleased
        // TODO add your handling code here:
         btnAlumnos1.setBackground(new Color(0, 119, 103));
    }//GEN-LAST:event_btnAlumnos1MouseReleased

    private void btnAlumnos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnos1ActionPerformed
        frmAlumnos obAlumnos = new frmAlumnos();
        obAlumnos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAlumnos1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPanelAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPanelAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPanelAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPanelAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPanelAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton btnAdministradores;
    private javax.swing.JButton btnAlumnos1;
    private javax.swing.JButton btnEquipos;
    private javax.swing.JButton btnPlantilla;
    private javax.swing.JButton btnPrestamos;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel iconSetting;
    private javax.swing.JLabel iconUsuarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblSubTitulo1;
    private javax.swing.JLabel lblSubTitulo2;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
